
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef MYMASTER_H
#define MYMASTER_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 MyMaster_valueRangeTest (UNS8 typeValue, void * value);
const indextable * MyMaster_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data MyMaster_Data;

#endif // MYMASTER_H
