
/* File generated by gen_cfile.py. Should not be modified. */

#include "MySlave.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

INTEGER32 Reservice = 0;

Index6000TypeDef MySlaveIndex6000_Unit;
Index6010TypeDef MySlaveIndex6010_DeviceCommand;
Index6011TypeDef MySlaveIndex6011_DeviceStatus;
Index6012TypeDef MySlaveIndex6012_DeviceFailureStatus;
Index6013TypeDef MySlaveIndex6013_DeviceStatusDelayTime;
Index6014TypeDef MySlaveIndex6014_DeviceFailureStatusDelayTime;
Index6020TypeDef MySlaveIndex6020_TemperatureActualValue;
Index6021TypeDef MySlaveIndex6021_TemperatureThreshold1;
Index6022TypeDef MySlaveIndex6022_TemperatureThreshold2;
Index6025TypeDef MySlaveIndex6025_TemperatureThreshold1ReturnValue;
Index6026TypeDef MySlaveIndex6026_TemperatureThreshold2ReturnValue;
Index6030TypeDef MySlaveIndex6030_OperatingHours;
Index6031TypeDef MySlaveIndex6031_DigitalInputConfiguration;
Index6032TypeDef MySlaveIndex6032_DigitalOutputConfiguration;
Index6100TypeDef MySlaveIndex6100_InputCommands;
Index6111TypeDef MySlaveIndex6111_InputStatus;
Index6112TypeDef MySlaveIndex6112_InputFailureStatus;
Index6113TypeDef MySlaveIndex6113_InputActualValues;
Index6114TypeDef MySlaveIndex6114_InputThreshold1Parameter;
Index6115TypeDef MySlaveIndex6115_InputThreshold2Parameter;
Index6118TypeDef MySlaveIndex6118_InputStatusDelayTime;
Index6119TypeDef MySlaveIndex6119_InputFailureStatusDelayTime;
Index611ATypeDef MySlaveIndex611A_InputThresholdReturn1Parameter;
Index611BTypeDef MySlaveIndex611B_InputThresholdReturn2Parameter;
Index6200TypeDef MySlaveIndex6200_Output1Commands;
Index6201TypeDef MySlaveIndex6201_Output1Status;
Index6202TypeDef MySlaveIndex6202_Output1FailureStatus;
Index6203TypeDef MySlaveIndex6203_Output1Range;
Index6204TypeDef MySlaveIndex6204_Output1ActualValues;
Index6205TypeDef MySlaveIndex6205_Output1SetValues;
Index6206TypeDef MySlaveIndex6206_Output1Sequence;
Index6207TypeDef MySlaveIndex6207_Output1TemperatureThresholds;
Index6200TypeDef MySlaveIndex6210_Output2Commands;
/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
#define valueRange_1 0xA0 /* Type INTEGER8, 0 < value < 10 */
UNS32 MySlave_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
    case valueRange_1:
      if (*(INTEGER8*)value < (INTEGER8)0) return OD_VALUE_TOO_LOW;
      if (*(INTEGER8*)value > (INTEGER8)10) return OD_VALUE_TOO_HIGH;
    break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 MySlave_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 MySlave_iam_a_slave = 1;

TIMER_HANDLE MySlave_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x0080 :   Actual bank record. */
                    UNS8 MySlave_highestSubIndex_obj0080 = 46; /* number of subindex - 1*/
                    UNS32 MySlave_obj0080[] = 
                    {
                      0x62050120,	
                      0x62050220,	
                      0x62050320,	
                      0x62050420,	
                      0x62050520,	
                      0x62050620,
                      0x62050720,
                      0x62050820,	
                      0x62050920,	
                      0x62050A20,	
                      0x62050B20,	
                      0x62050C20,	
                      0x62050D20,
                      0x62050E20,
                      0x62050F20,	
                      0x62051020,	
                      0x62051120,	
                      0x62051220,	
                      0x62051320,	
                      0x62051420,
                      0x62051520,
                      0x62051620,	
                      0x62051720,	
                      0x62051820,	
                      0x62051920,	
                      0x62051A20,	
                      0x62051B20,	
                      0x62051C20,	
                      0x62051D20,	
                      0x62051E20,	
                      0x62051F20,	
                      0x62052020,
                      0x62052120,
                      0x62052220,	
                      0x62052320,	
                      0x62052420,	
                      0x62052520,	
                      0x62052620,	
                      0x62052720,
                      0x62052820,
                      0x62052920,	
                      0x62052A20,	
                      0x62052B20,	
                      0x62052C20,	
                      0x62052D20,	
                      0x62052E20,
                    };
                    subindex MySlave_Index0080[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj0080, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[5], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[6], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[7], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[8], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[9], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[10], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[11], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[12], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[13], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[14], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[15], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[16], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[17], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[18], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[19], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[20], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[21], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[22], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[23], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[24], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[25], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[26], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[27], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[28], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[28], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[30], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[31], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[32], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[33], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[34], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[35], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[36], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[37], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[38], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[39], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[40], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[41], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[42], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[43], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[44], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0080[45], NULL },
                     };

/* index 0x0081 :   Input values record. */
                    UNS8 MySlave_highestSubIndex_obj0081 = 5; /* number of subindex - 1*/
                    UNS32 MySlave_obj0081[] = 
                    {
                      0x62000120,	
                      0x60000220,
                      0x60000320,
                      0x60000420,
                      0x60000520,
                    };
                    subindex MySlave_Index0081[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj0081, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0081[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0081[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0081[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0081[3], NULL },
                       { RW, uint32, sizeof (UNS16), (void*)&MySlave_obj0081[4], NULL },
                     };

/* index 0x0082 :   Output ranges record. */
                    UNS8 MySlave_highestSubIndex_obj0082 = 5; /* number of subindex - 1*/
                    UNS32 MySlave_obj0082[] = 
                    {
                      0x62030120,
                      0x62030120,
                      0x62030120,
                      0x62030120,
                      0x62030120,
                    };
                    subindex MySlave_Index0082[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj0082, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0082[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0082[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0082[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0082[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0082[4], NULL },
                     };

/* index 0x0083 :   Output actual values record. */
                    UNS8 MySlave_highestSubIndex_obj0083 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj0083[] = 
                    {
                      0x62040120,
                      0x62040220,
                      0x62040320,
                      0x62040420,
                      0x62040520,
                      0x62040620,
                    };
                    subindex MySlave_Index0083[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj0083, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[4], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0083[5], NULL },
                     };

/* index 0x0084 :   Output temperature thresholds record. */
                    UNS8 MySlave_highestSubIndex_obj0084 = 5; /* number of subindex - 1*/
                    UNS32 MySlave_obj0084[] = 
                    {
                      0x62070120,
                      0x62070220,
                      0x62070320,
                      0x62070420,
                      0x62070520,
                    };
                    subindex MySlave_Index0084[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj0084, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0084[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0084[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0084[2], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0084[3], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj0084[4], NULL },
                     };

/* index 0x1000 :   Device Type. */
                    UNS32 MySlave_obj1000 = 0x0;	/* 0 */
                    subindex MySlave_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 MySlave_obj1001 = 0x0;	/* 0 */
                    subindex MySlave_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 MySlave_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 MySlave_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex MySlave_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 MySlave_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 MySlave_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 MySlave_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 MySlave_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 MySlave_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 MySlave_highestSubIndex_obj1016 = 0;
                    UNS32 MySlave_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 MySlave_obj1017 = 1000;	/* 0 */
                    subindex MySlave_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 MySlave_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 MySlave_obj1018_Vendor_ID = 0x11223344;	/* 0 */
                    UNS32 MySlave_obj1018_Product_Code = 0x55667788;	/* 0 */
                    UNS32 MySlave_obj1018_Revision_Number = 0x99aabbcc;	/* 0 */
                    UNS32 MySlave_obj1018_Serial_Number = 0x12345678;	/* 0 */
                    subindex MySlave_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&MySlave_obj1018_Serial_Number, NULL }
                     };

/* index 0x1200 :   Server SDO 1 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1200 = 3; /* number of subindex - 1*/
                    UNS32 MySlave_obj1200_COB_ID_Client_to_Server_Transmit_SDO = 0x600;	/* 1536 */
                    UNS32 MySlave_obj1200_COB_ID_Server_to_Client_Receive_SDO = 0x580;	/* 1408 */
                    UNS8 MySlave_obj1200_Node_ID_of_the_SDO_Server = 0x8;	/* 8 */
                    const subindex MySlave_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), .pObject = &MySlave_highestSubIndex_obj1200 },
                       { RW, uint32, sizeof (UNS32),.pObject = &MySlave_obj1200_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), .pObject = &MySlave_obj1200_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), .pObject = &MySlave_obj1200_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 MySlave_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MySlave_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 MySlave_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1400, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1400_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1400_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1400_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1400_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1400_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1400_SYNC_start_value, NULL }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 MySlave_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MySlave_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 MySlave_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1401, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1401_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1401_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1401_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1401_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1401_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1401_SYNC_start_value, NULL }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 MySlave_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MySlave_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 MySlave_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1402, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1402_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1402_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1402_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1402_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1402_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1402_SYNC_start_value, NULL }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 MySlave_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 MySlave_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 MySlave_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1403, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1403_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1403_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1403_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1403_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1403_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1403_SYNC_start_value, NULL }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1600 = 4; /* number of subindex - 1*/
                    UNS32 MySlave_obj1600[] = 
                    {
                      0x62000208,	
                      0x62000308,	
                      0x62100208,	
                      0x62100308,	
                    };
                    subindex MySlave_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1600, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1600[0], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1600[1], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1600[2], NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1600[3], NULL },
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1601 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1601[] = 
                    {
                      0x62050108,	                     
                    };
                    subindex MySlave_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1601, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1601[0], NULL },
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1602 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1602[] = 
                    {
                      0x62050820,	                
                    };
                    subindex MySlave_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1602, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1602[0], NULL },
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1603 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1603[] = 
                    {
                      0x62050F20,	
                    };
                    subindex MySlave_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1603, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1603[0], NULL },
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 MySlave_obj1800_Transmission_Type = 0xFE;	/* 10 */
                    UNS16 MySlave_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1800_Event_Timer = 1000;	/* 0 */
                    UNS8 MySlave_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1800, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1800_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1800_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1800_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1800_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1800_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1800_SYNC_start_value, NULL }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 MySlave_obj1801_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 MySlave_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1801_Event_Timer = 1000;	/* 0 */
                    UNS8 MySlave_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1801, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1801_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1801_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1801_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1801_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1801_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1801_SYNC_start_value, NULL }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 MySlave_obj1802_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 MySlave_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1802_Event_Timer = 1000;	/* 0 */
                    UNS8 MySlave_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1802, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1802_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1802_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1802_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1802_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1802_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1802_SYNC_start_value, NULL }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 MySlave_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 MySlave_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 MySlave_obj1803_Transmission_Type = 0xFE;	/* 254 */
                    UNS16 MySlave_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 MySlave_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 MySlave_obj1803_Event_Timer = 1000;	/* 100 */
                    UNS8 MySlave_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    subindex MySlave_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1803, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1803_COB_ID_used_by_PDO, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1803_Transmission_Type, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1803_Inhibit_Time, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1803_Compatibility_Entry, NULL },
                       { RW, uint16, sizeof (UNS16), (void*)&MySlave_obj1803_Event_Timer, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_obj1803_SYNC_start_value, NULL }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1A00 = 4; /* number of subindex - 1*/
                    UNS32 MySlave_obj1A00[] = 
                    {
                      0x60110120,
                      0x60120120,
                    };
                    subindex MySlave_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1A00, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A00[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A00[1], NULL },
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1A01 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1A01[] = 
                    {
                      0x62040120,	
                      0x62140120,	
                    };
                    subindex MySlave_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1A01, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A01[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A01[1], NULL },
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1A02 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1A02[] = 
                    {
                      0x61130120,	
                      0x21000008,
                    };
                    subindex MySlave_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1A02, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A02[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A02[1], NULL },
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 MySlave_highestSubIndex_obj1A03 = 1; /* number of subindex - 1*/
                    UNS32 MySlave_obj1A03[] = 
                    {
                      0x61130120,//0x20010108,	
                    };
                    subindex MySlave_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj1A03, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&MySlave_obj1A03[0], NULL },
                     };

/* index 0x6000 :   SI unit and prefix */
                    UNS8 MySlave_highestSubIndex_obj6000 = 6; /* number of subindex - 1*/
                    subindex MySlave_Index6000[] = 
                     {
                       { RO, uint8, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj6000, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Voltage, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Current, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Power, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Frequency, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Temperature, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6000_Unit.Time, NULL },
                     };

/* index 0x6010 :   General device commands */
                    UNS8 MySlave_highestSubIndex_obj6010 = 4; /* number of subindex - 1*/
                    subindex MySlave_Index6010[] = 
                     {
                       { RO, uint8, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj6010, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6010_DeviceCommand.ControlMode, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6010_DeviceCommand.QuitFailure, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6010_DeviceCommand.Look, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6010_DeviceCommand.SelfStart, NULL },
                     };

/* index 0x6011 :   Device status */
                    UNS8 MySlave_highestSubIndex_obj6011 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6011[] = 
                     {
                       { RO, uint8, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj6011, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6011_DeviceStatus.Condition, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6011_DeviceStatus.Logic, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6011_DeviceStatus.Event, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6011_DeviceStatus.FailureStatus, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6011_DeviceStatus.FailureIndication, NULL },
                     };

/* index 0x6012 :   Device failure status */
                    UNS8 MySlave_highestSubIndex_obj6012 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6012[] = 
                     {
                       { RO, uint8, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj6012, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6012_DeviceFailureStatus.Condition, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6012_DeviceFailureStatus.Logic, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6012_DeviceFailureStatus.Event, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6012_DeviceFailureStatus.FailureStatus, NULL },
                       { RO, uint8, sizeof (UNS32), (void*)&MySlaveIndex6012_DeviceFailureStatus.FailureIndication, NULL },
                     };

/* index 0x6013 :   Device status delay time */
                    UNS8 MySlave_highestSubIndex_obj6013 = 16; /* number of subindex - 1*/
                    subindex MySlave_Index6013[] = 
                     {
                       { RO, uint8, sizeof (UNS32), (void*)&MySlave_highestSubIndex_obj6013, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.InputDelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output1DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output2DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output3DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output4DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output5DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output6DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output7DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.Output8DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.MainSwitchDelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.InterlockDelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.KeyLockDelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&Reservice, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&Reservice, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.DeveiceSpecificSignal1DelayTime, NULL },
                       { RW, uint8, sizeof (UNS32), (void*)&MySlaveIndex6013_DeviceStatusDelayTime.DeveiceSpecificSignal2DelayTime, NULL },
                     };

/* index 0x6014 :   Device failure status delay time */
                    UNS8 MySlave_highestSubIndex_obj6014 = 14; /* number of subindex - 1*/
                    subindex MySlave_Index6014[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6014, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.InputDelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output1DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output2DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output3DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output4DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output5DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output6DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output7DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.Output8DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.MainSwitchDelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.InterlockDelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.KeyLockDelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Reservice, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&Reservice, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.DeveiceSpecificSignal1DelayTime, NULL },
                       { RW, uint8, sizeof (UNS8), (void*)&MySlaveIndex6014_DeviceFailureStatusDelayTime.DeveiceSpecificSignal2DelayTime, NULL },
                     };

/* index 0x6020 :   Temperature actual value */
                    // UNS8 MySlave_highestSubIndex_obj6021 = 1; /* number of subindex - 1*/
                    subindex MySlave_Index6020[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6020_TemperatureActualValue.Value, NULL },
                     };

/* index 0x6021 :   Temperature threshold1 */
                    // UNS8 MySlave_highestSubIndex_obj6021 = 1; /* number of subindex - 1*/
                    subindex MySlave_Index6021[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6021_TemperatureThreshold1.Value, NULL },
                     };

/* index 0x6022 :   Temperature threshold1 */
                    // UNS8 MySlave_highestSubIndex_obj6022 = 1; /* number of subindex - 1*/
                    subindex MySlave_Index6022[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6022_TemperatureThreshold2.Value, NULL },
                     };

/* index 0x6025 :   Temperature threshold1 return value */
                    UNS8 MySlave_highestSubIndex_obj6025 = 0; /* number of subindex - 1*/
                    subindex MySlave_Index6025[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6025_TemperatureThreshold1ReturnValue.TemperatureThreshold1ReturenValue, NULL },
                     };

/* index 0x6026 :   Temperature threshold2 return value */
                    UNS8 MySlave_highestSubIndex_obj6026 = 0; /* number of subindex - 1*/
                    subindex MySlave_Index6026[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6026_TemperatureThreshold2ReturnValue.TemperatureThreshold2ReturenValue, NULL },
                     };

/* index 0x6030 :   Operating hours */
                    UNS8 MySlave_highestSubIndex_obj6030 = 0; /* number of subindex - 1*/
                    subindex MySlave_Index6030[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlaveIndex6030_OperatingHours.Value, NULL },
                     };

/* index 0x6031 :   Operating hours */
                    UNS8 MySlave_highestSubIndex_obj6031 = 3; /* number of subindex - 1*/
                    subindex MySlave_Index6031[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6031, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6031_DigitalInputConfiguration.DigitalInput1Condiguration, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6031_DigitalInputConfiguration.DigitalInput2Condiguration, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6031_DigitalInputConfiguration.DigitalInput3Condiguration, NULL },
                     };

/* index 0x6032 :   Operating hours */
                    UNS8 MySlave_highestSubIndex_obj6032 = 6; /* number of subindex - 1*/
                    subindex MySlave_Index6032[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6032, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput1Condiguration, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput1Condiguration_Threshold, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput2Condiguration, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput2Condiguration_Threshold, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput3Condiguration, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6032_DigitalOutputConfiguration.DigitalOutput3Condiguration_Threshold, NULL },
                     };

/* index 0x6100 :   Input command */
                    UNS8 MySlave_highestSubIndex_obj6100 = 2; /* number of subindex - 1*/
                    subindex MySlave_Index6100[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6100, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6100_InputCommands.OnOff, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6100_InputCommands.QuitFailure, NULL },
                     };

/* index 0x6111 :   Input status */
                    UNS8 MySlave_highestSubIndex_obj6111 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6111[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6111, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6111_InputStatus.Condition, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6111_InputStatus.Logic, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6111_InputStatus.Event, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6111_InputStatus.FaultStatus, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6111_InputStatus.FaultIndication, NULL },
                     };

/* index 0x6112 :   Input status */
                    UNS8 MySlave_highestSubIndex_obj6112 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6112[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6112, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6112_InputFailureStatus.Condition, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6112_InputFailureStatus.Logic, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6112_InputFailureStatus.Event, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6112_InputFailureStatus.FaultStatus, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6112_InputFailureStatus.FaultIndication, NULL },
                     };

/* index 0x6113 :   Input actual values */
                    UNS8 MySlave_highestSubIndex_obj6113 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6113[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6113, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6113_InputActualValues.Voltage, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6113_InputActualValues.Current, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6113_InputActualValues.Power, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6113_InputActualValues.LinkVoltage, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6113_InputActualValues.Temperature, NULL },
                     };

/* index 0x6114 :   Input threshold 1 parameters */
                    UNS8 MySlave_highestSubIndex_obj6114 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6114[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6114, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6114_InputThreshold1Parameter.Voltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6114_InputThreshold1Parameter.Current, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6114_InputThreshold1Parameter.Power, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6114_InputThreshold1Parameter.LinkVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6114_InputThreshold1Parameter.Temperature, NULL },
                     };

/* index 0x6115 :   Input threshold 1 parameters */
                    UNS8 MySlave_highestSubIndex_obj6115 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6115[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6115, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6115_InputThreshold2Parameter.Voltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6115_InputThreshold2Parameter.Current, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6115_InputThreshold2Parameter.Power, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6115_InputThreshold2Parameter.LinkVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6115_InputThreshold2Parameter.Temperature, NULL },
                     };

/* index 0x6118 :   Input status delay time */
                    UNS8 MySlave_highestSubIndex_obj6118 = 10; /* number of subindex - 1*/
                    subindex MySlave_Index6118[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6118, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.InputDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.VControlDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.CControlDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.PControlDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.DeviceSpecificSignal1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.CControlDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.DeviceSpecificSignal1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.DeviceSpecificSignal2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.DeviceSpecificSignal3DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6118_InputStatusDelayTime.DeviceSpecificSignal4DelayTime, NULL },
                     };

/* index 0x6119 :   Input failure status delay time */
                    UNS8 MySlave_highestSubIndex_obj6119 = 16; /* number of subindex - 1*/
                    subindex MySlave_Index6119[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6119, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.VThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.VThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.CThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.CThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.PThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.PThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.LvThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.LvThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.TThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.TThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.OverVoltageDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.CoolingFaultDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.PowerFailDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.DeviceSpecificSignal1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6119_InputFailureStatusDelayTime.DeviceSpecificSignal2DelayTime, NULL },
                     };

/* index 0x611A :   Input threshold 1 return parameters */
                    UNS8 MySlave_highestSubIndex_obj611A = 5; /* number of subindex - 1*/
                    subindex MySlave_Index611A[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj611A, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611A_InputThresholdReturn1Parameter.Voltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611A_InputThresholdReturn1Parameter.Current, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611A_InputThresholdReturn1Parameter.Power, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611A_InputThresholdReturn1Parameter.LinkVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611A_InputThresholdReturn1Parameter.Temperature, NULL },
                     };

/* index 0x611B :   Input threshold 2 return parameters */
                    UNS8 MySlave_highestSubIndex_obj611B = 5; /* number of subindex - 1*/
                    subindex MySlave_Index611B[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj611B, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611B_InputThresholdReturn2Parameter.Voltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611B_InputThresholdReturn2Parameter.Current, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611B_InputThresholdReturn2Parameter.Power, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611B_InputThresholdReturn2Parameter.LinkVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex611B_InputThresholdReturn2Parameter.Temperature, NULL },
                     };

/* index 0x6200 :   Output 1 commands */
                    UNS8 MySlave_highestSubIndex_obj6200 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6200, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6200_Output1Commands.OpetationMode, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6200_Output1Commands.OnOff, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6200_Output1Commands.QuitFailure, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6200_Output1Commands.Bank, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6200_Output1Commands.SelfStarting, NULL },
                     };

/* index 0x6201 :   Output 1 status */
                    UNS8 MySlave_highestSubIndex_obj6201 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6201[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6201, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6201_Output1Status.Condtion, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6201_Output1Status.Logic, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6201_Output1Status.Event, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6201_Output1Status.FaultStatus, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6201_Output1Status.FaultIndicaion, NULL },
                     };

/* index 0x6202 :   Output 1 failure status */
                    UNS8 MySlave_highestSubIndex_obj6202 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6202[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6202, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6202_Output1FailureStatus.Condtion, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6202_Output1FailureStatus.Logic, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6202_Output1FailureStatus.Event, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6202_Output1FailureStatus.FaultStatus, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6202_Output1FailureStatus.FaultIndicaion, NULL },
                     };

/* index 0x6203 :   Output 1 ranges */
                    UNS8 MySlave_highestSubIndex_obj6203 = 8; /* number of subindex - 1*/
                    subindex MySlave_Index6203[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6203, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.VoltageMax, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.VoltageMin, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.CurrentMax, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.CurrentMin, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.PowerMax, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.PowerMin, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.FrequencyMax, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6203_Output1Range.FrequencyMin, NULL },
                     };

/* index 0x6204 :   Output 1 actual values */
                    UNS8 MySlave_highestSubIndex_obj6204 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6204[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6204, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6204_Output1ActualValues.Voltage, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6204_Output1ActualValues.Current, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6204_Output1ActualValues.Power, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6204_Output1ActualValues.LinkVoltage, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6204_Output1ActualValues.Temperature, NULL },
                     };
/* index 0x6205 :   Output 1 set values */
                    UNS8 MySlave_highestSubIndex_obj6205 = 38; /* number of subindex - 1*/
                    subindex MySlave_Index6205[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6205, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MaxVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MinVoltage, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThreshold1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThreshold2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.SetCurrent, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MaxCurrent, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MinCurrent, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThreshold1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThreshold2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.SetPower, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MaxPower, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MinPower, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThreshold1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThreshold2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.SetFrequency, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MaxFrequency, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.MinFrequency, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThreshold1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThreshold2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThreshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThreshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.V_ControlFlagDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.C_ControlFlagDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.P_ControlFlagDelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.F_ControlFlagDelayTimF, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificStatusFlag1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificStatusFlag2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificStatusFlag3DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificStatusFlag4DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificFailureStatusFlag1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.DeviceSpecificFailureStatusFlag2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThresholdReturn1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.VoltageThresholdReturn2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThresholdReturn1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.CurrentThresholdReturn2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThresholdReturn1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.PowerThresholdReturn2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThresholdReturn1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6205_Output1SetValues.FrequencyThresholdReturn2, NULL },
                     };

/* index 0x6206 :   Output 1 sequence */
                    UNS8 MySlave_highestSubIndex_obj6206 = 10; /* number of subindex - 1*/
                    subindex MySlave_Index6206[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6206, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.Mode, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.Restart, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.ActualLoopNo, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.ActualStepNo, NULL },
                       { RO, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.ActualStepTme, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.SetLoopNo, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.SetStepNo, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.SetSteptype, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.SetStepTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6206_Output1Sequence.SetStepBank, NULL },
                     };

/* index 0x6207 :   Output 1 temperature thresholds */
                    UNS8 MySlave_highestSubIndex_obj6207 = 6; /* number of subindex - 1*/
                    subindex MySlave_Index6207[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6207, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.Threshold1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.Threshold2, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.Threshold1DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.Threshold2DelayTime, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.ThresholdReturen1, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6207_Output1TemperatureThresholds.ThresholdReturen2, NULL },
                     };

/* index 0x6210 :   Output 2 commands */
                    UNS8 MySlave_highestSubIndex_obj6210 = 5; /* number of subindex - 1*/
                    subindex MySlave_Index6210[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&MySlave_highestSubIndex_obj6210, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6210_Output2Commands.OpetationMode, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6210_Output2Commands.OnOff, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6210_Output2Commands.QuitFailure, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6210_Output2Commands.Bank, NULL },
                       { RW, int32, sizeof (INTEGER32), (void*)&MySlaveIndex6210_Output2Commands.SelfStarting, NULL },
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable MySlave_objdict[] = 
{
  { (subindex*)MySlave_Index1000,sizeof(MySlave_Index1000)/sizeof(MySlave_Index1000[0]), 0x1000},
  { (subindex*)MySlave_Index1001,sizeof(MySlave_Index1001)/sizeof(MySlave_Index1001[0]), 0x1001},
  { (subindex*)MySlave_Index1017,sizeof(MySlave_Index1017)/sizeof(MySlave_Index1017[0]), 0x1017},
  { (subindex*)MySlave_Index1018,sizeof(MySlave_Index1018)/sizeof(MySlave_Index1018[0]), 0x1018},
  { (subindex*)MySlave_Index1200,sizeof(MySlave_Index1200)/sizeof(MySlave_Index1200[0]), 0x1200},
  { (subindex*)MySlave_Index1400,sizeof(MySlave_Index1400)/sizeof(MySlave_Index1400[0]), 0x1400},
  { (subindex*)MySlave_Index1401,sizeof(MySlave_Index1401)/sizeof(MySlave_Index1401[0]), 0x1401},
  { (subindex*)MySlave_Index1402,sizeof(MySlave_Index1402)/sizeof(MySlave_Index1402[0]), 0x1402},
  { (subindex*)MySlave_Index1403,sizeof(MySlave_Index1403)/sizeof(MySlave_Index1403[0]), 0x1403},
  { (subindex*)MySlave_Index1600,sizeof(MySlave_Index1600)/sizeof(MySlave_Index1600[0]), 0x1600},
  { (subindex*)MySlave_Index1601,sizeof(MySlave_Index1601)/sizeof(MySlave_Index1601[0]), 0x1601},
  { (subindex*)MySlave_Index1602,sizeof(MySlave_Index1602)/sizeof(MySlave_Index1602[0]), 0x1602},
  { (subindex*)MySlave_Index1603,sizeof(MySlave_Index1603)/sizeof(MySlave_Index1603[0]), 0x1603},
  { (subindex*)MySlave_Index1800,sizeof(MySlave_Index1800)/sizeof(MySlave_Index1800[0]), 0x1800},
  { (subindex*)MySlave_Index1801,sizeof(MySlave_Index1801)/sizeof(MySlave_Index1801[0]), 0x1801},
  { (subindex*)MySlave_Index1802,sizeof(MySlave_Index1802)/sizeof(MySlave_Index1802[0]), 0x1802},
  { (subindex*)MySlave_Index1803,sizeof(MySlave_Index1803)/sizeof(MySlave_Index1803[0]), 0x1803},
  { (subindex*)MySlave_Index1A00,sizeof(MySlave_Index1A00)/sizeof(MySlave_Index1A00[0]), 0x1A00},
  { (subindex*)MySlave_Index1A01,sizeof(MySlave_Index1A01)/sizeof(MySlave_Index1A01[0]), 0x1A01},
  { (subindex*)MySlave_Index1A02,sizeof(MySlave_Index1A02)/sizeof(MySlave_Index1A02[0]), 0x1A02},
  { (subindex*)MySlave_Index1A03,sizeof(MySlave_Index1A03)/sizeof(MySlave_Index1A03[0]), 0x1A03},
  { (subindex*)MySlave_Index6000,sizeof(MySlave_Index6000)/sizeof(MySlave_Index6000[0]), 0x6000},
  { (subindex*)MySlave_Index6010,sizeof(MySlave_Index6010)/sizeof(MySlave_Index6010[0]), 0x6010},
  { (subindex*)MySlave_Index6011,sizeof(MySlave_Index6011)/sizeof(MySlave_Index6011[0]), 0x6011},
  { (subindex*)MySlave_Index6012,sizeof(MySlave_Index6012)/sizeof(MySlave_Index6012[0]), 0x6012},
  { (subindex*)MySlave_Index6013,sizeof(MySlave_Index6013)/sizeof(MySlave_Index6013[0]), 0x6013},
  { (subindex*)MySlave_Index6014,sizeof(MySlave_Index6014)/sizeof(MySlave_Index6014[0]), 0x6014},
  { (subindex*)MySlave_Index6021,sizeof(MySlave_Index6021)/sizeof(MySlave_Index6021[0]), 0x6021},
  { (subindex*)MySlave_Index6022,sizeof(MySlave_Index6022)/sizeof(MySlave_Index6022[0]), 0x6022},
  { (subindex*)MySlave_Index6025,sizeof(MySlave_Index6025)/sizeof(MySlave_Index6025[0]), 0x6025},
  { (subindex*)MySlave_Index6026,sizeof(MySlave_Index6026)/sizeof(MySlave_Index6026[0]), 0x6026},
  { (subindex*)MySlave_Index6030,sizeof(MySlave_Index6030)/sizeof(MySlave_Index6030[0]), 0x6030},
  { (subindex*)MySlave_Index6031,sizeof(MySlave_Index6031)/sizeof(MySlave_Index6031[0]), 0x6031},
  { (subindex*)MySlave_Index6032,sizeof(MySlave_Index6032)/sizeof(MySlave_Index6032[0]), 0x6032},
  { (subindex*)MySlave_Index6111,sizeof(MySlave_Index6111)/sizeof(MySlave_Index6111[0]), 0x6111},
  { (subindex*)MySlave_Index6112,sizeof(MySlave_Index6112)/sizeof(MySlave_Index6112[0]), 0x6112},
  { (subindex*)MySlave_Index6113,sizeof(MySlave_Index6113)/sizeof(MySlave_Index6113[0]), 0x6113},
  { (subindex*)MySlave_Index6114,sizeof(MySlave_Index6114)/sizeof(MySlave_Index6114[0]), 0x6114},
  { (subindex*)MySlave_Index6115,sizeof(MySlave_Index6115)/sizeof(MySlave_Index6115[0]), 0x6115},
  { (subindex*)MySlave_Index6118,sizeof(MySlave_Index6118)/sizeof(MySlave_Index6118[0]), 0x6118},
  { (subindex*)MySlave_Index6119,sizeof(MySlave_Index6119)/sizeof(MySlave_Index6119[0]), 0x6119},
  { (subindex*)MySlave_Index611A,sizeof(MySlave_Index611A)/sizeof(MySlave_Index611A[0]), 0x611A},
  { (subindex*)MySlave_Index611B,sizeof(MySlave_Index611B)/sizeof(MySlave_Index611B[0]), 0x611B},
  { (subindex*)MySlave_Index6200,sizeof(MySlave_Index6200)/sizeof(MySlave_Index6200[0]), 0x6200},
  { (subindex*)MySlave_Index6201,sizeof(MySlave_Index6201)/sizeof(MySlave_Index6201[0]), 0x6201},
  { (subindex*)MySlave_Index6202,sizeof(MySlave_Index6202)/sizeof(MySlave_Index6202[0]), 0x6202},
  { (subindex*)MySlave_Index6203,sizeof(MySlave_Index6203)/sizeof(MySlave_Index6203[0]), 0x6203},
  { (subindex*)MySlave_Index6204,sizeof(MySlave_Index6204)/sizeof(MySlave_Index6204[0]), 0x6204},
  { (subindex*)MySlave_Index6205,sizeof(MySlave_Index6205)/sizeof(MySlave_Index6205[0]), 0x6205},
  { (subindex*)MySlave_Index6206,sizeof(MySlave_Index6206)/sizeof(MySlave_Index6206[0]), 0x6206},
  { (subindex*)MySlave_Index6207,sizeof(MySlave_Index6207)/sizeof(MySlave_Index6207[0]), 0x6207},
  { (subindex*)MySlave_Index6210,sizeof(MySlave_Index6210)/sizeof(MySlave_Index6210[0]), 0x6210},
};

const indextable * MySlave_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1017: i = 2;break;
		case 0x1018: i = 3;break;
		case 0x1200: i = 4;break;
		case 0x1400: i = 5;break;
		case 0x1401: i = 6;break;
		case 0x1402: i = 7;break;
		case 0x1403: i = 8;break;
		case 0x1600: i = 9;break;
		case 0x1601: i = 10;break;
		case 0x1602: i = 11;break;
		case 0x1603: i = 12;break;
		case 0x1800: i = 13;break;
		case 0x1801: i = 14;break;
		case 0x1802: i = 15;break;
		case 0x1803: i = 16;break;
		case 0x1A00: i = 17;break;
		case 0x1A01: i = 18;break;
		case 0x1A02: i = 19;break;
		case 0x1A03: i = 20;break;
    case 0x6000: i = 21;break;
    case 0x6010: i = 22;break;
    case 0x6011: i = 23;break;
    case 0x6012: i = 24;break;
    case 0x6013: i = 25;break;
    case 0x6014: i = 26;break;
    case 0x6021: i = 27;break;
    case 0x6022: i = 28;break;
    case 0x6025: i = 29;break;
    case 0x6026: i = 30;break;
    case 0x6030: i = 31;break;
    case 0x6031: i = 32;break;
    case 0x6032: i = 33;break;
    case 0x6111: i = 34;break;
    case 0x6112: i = 35;break;
    case 0x6113: i = 36;break;
    case 0x6114: i = 37;break;
    case 0x6115: i = 38;break;
    case 0x6118: i = 39;break;
    case 0x6119: i = 40;break;
    case 0x611A: i = 41;break;
    case 0x611B: i = 42;break;
    case 0x6200: i = 43;break;
    case 0x6201: i = 44;break;
    case 0x6202: i = 45;break;
    case 0x6203: i = 46;break;
    case 0x6204: i = 47;break;
    case 0x6205: i = 48;break;
    case 0x6206: i = 49;break;
    case 0x6207: i = 50;break;
    case 0x6210: i = 51;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &MySlave_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status MySlave_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index MySlave_firstIndex = {
  4, /* SDO_SVR */
  4, /* SDO_CLT */
  5, /* PDO_RCV */
  9, /* PDO_RCV_MAP */
  13, /* PDO_TRS */
  17 /* PDO_TRS_MAP */
};

const quick_index MySlave_lastIndex = {
  4, /* SDO_SVR */
  4, /* SDO_CLT */
  8, /* PDO_RCV */
  12, /* PDO_RCV_MAP */
  16, /* PDO_TRS */
  20 /* PDO_TRS_MAP */
};

const UNS16 MySlave_ObjdictSize = sizeof(MySlave_objdict)/sizeof(MySlave_objdict[0]); 

CO_Data MySlave_Data = CANOPEN_NODE_DATA_INITIALIZER(MySlave);

