/**
  ******************************************************************************
  * @file    PDS_PeripheralKSZ8081.c
  * @author  WuYi
  * @brief   This file initialize kzs8081. Firstly, set up the corresponding pins
  * for net card driver. Secondly, configure the interrupt.
  ******************************************************************************
**/

/* Includes ------------------------------------------------------------------*/
#include "data_type.h"
#include "PDS_PeripheralKSZ8081.h"
#include "PDS_SocTICK.h" 


BOOL_t PDS_peripheral_ksz8081_init(void)
{
	REG_BIT_SET(RCC->AHB1ENR,0);
	REG_BIT_SET(RCC->AHB1ENR,2);
	REG_BIT_SET(RCC->AHB1ENR,6);
	REG_BIT_SET(RCC->AHB1ENR,8);
	REG_BIT_SET(RCC->APB2ENR,14);
	REG_BIT_SET(SYSCFG->PMC,23);

	/* ENET_RMII_REF_CLK */
	Px_MODER_SET(GPIOA,PIN1,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOA,PIN1,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOA,PIN1,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOA,PIN1,CFG_OTYPE_PP);
	Px_AF_SET(GPIOA,PIN1,AF11);
	/* ENET_MDIO */
	Px_MODER_SET(GPIOA,PIN2,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOA,PIN2,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOA,PIN2,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOA,PIN2,CFG_OTYPE_PP);
	Px_AF_SET(GPIOA,PIN2,AF11);
	/* ENET_CRS_DV */
	Px_MODER_SET(GPIOA,PIN7,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOA,PIN7,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOA,PIN7,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOA,PIN7,CFG_OTYPE_PP);
	Px_AF_SET(GPIOA,PIN7,AF11);
	/* ENET_MDC */
	Px_MODER_SET(GPIOC,PIN1,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOC,PIN1,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOC,PIN1,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOC,PIN1,CFG_OTYPE_PP);
	Px_AF_SET(GPIOC,PIN1,AF11);
	/* ENET_RXD0 */
	Px_MODER_SET(GPIOC,PIN4,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOC,PIN4,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOC,PIN4,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOC,PIN4,CFG_OTYPE_PP);
	Px_AF_SET(GPIOC,PIN4,AF11);
	/* ENET_RXD1 */
	Px_MODER_SET(GPIOC,PIN5,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOC,PIN5,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOC,PIN5,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOC,PIN5,CFG_OTYPE_PP);
	Px_AF_SET(GPIOC,PIN5,AF11);
	/* ENET_TX_EN */
	Px_MODER_SET(GPIOG,PIN11,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOG,PIN11,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOG,PIN11,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOG,PIN11,CFG_OTYPE_PP);
	Px_AF_SET(GPIOG,PIN11,AF11);
	/* ENET_TXD0 */
	Px_MODER_SET(GPIOG,PIN13,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOG,PIN13,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOG,PIN13,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOG,PIN13,CFG_OTYPE_PP);
	Px_AF_SET(GPIOG,PIN13,AF11);
	/* ENET_TXD1 */
	Px_MODER_SET(GPIOG,PIN14,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOG,PIN14,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOG,PIN14,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOG,PIN14,CFG_OTYPE_PP);
	Px_AF_SET(GPIOG,PIN14,AF11);
	/* ENET_RX_ER */
	Px_MODER_SET(GPIOI,PIN10,CFG_MODE_AF);
	Px_OSPEEDR_SET(GPIOI,PIN10,CFG_SPEED_100M);
	Px_PUPDR_SET(GPIOI,PIN10,CFG_PUPD_PU);
	Px_OTYPER_SET(GPIOI,PIN10,CFG_OTYPE_PP);
	Px_AF_SET(GPIOI,PIN10,AF11);
	
 	PDS_soc_tick_delay_ms(50);

 	SOC_nvic_init(8,0,ETH_IRQn,4);//配置ETH中的分组

	return BOOL_TRUE;

}

U8_t PDS_peripheral_ksz8081_get_speed(void)
{
	U8_t speed = 6;

	//speed=((ETH_ReadPHYRegister(0x00,31)&0x1C)>>2); 
	//从LAN8720的31号寄存器中读取网络速度和双工模式

	return speed;
}

BOOL_t PDS_peripheral_ksz8081_set_led_mode(U8_t mode)
{
	if (mode)
	{
		return BOOL_FALSE;
	}

	return BOOL_TRUE;
}



